export const NIGERIAN_CROPS = [
  'Acha (Fonio)',
  'African eggplant',
  'African yam bean',
  'Amaranth',
  'Avocado',
  'Banana',
  'Bambara groundnut',
  'Beans (Cowpea)',
  'Bitter leaf',
  'Cabbage',
  'Calabash melon (Egusi)',
  'Carrot',
  'Cashew',
  'Cassava',
  'Cayenne pepper',
  'Citrus',
  'Cocoa',
  'Coconut',
  'Coffee',
  'Cocoyam',
  'Cotton',
  'Cucumber',
  'Date palm',
  'Garden egg',
  'Garlic',
  'Ginger',
  'Guava',
  'Groundnut',
  'Irish potato',
  'Jute mallow (Ewedu)',
  'Kola nut',
  'Lettuce',
  'Lime',
  'Maize',
  'Mango',
  'Millet',
  'Okra',
  'Oil palm',
  'Onion',
  'Orange',
  'Papaya (Pawpaw)',
  'Passion fruit',
  'Pepper (Ata rodo)',
  'Pineapple',
  'Plantain',
  'Pumpkin (Ugu)',
  'Rice',
  'Rubber',
  'Sesame (Beniseed)',
  'Sorghum',
  'Soybean',
  'Spinach',
  'Sugarcane',
  'Sweet potato',
  'Tangerine',
  'Tomato',
  'Turmeric',
  'Waterleaf',
  'Watermelon',
  'Wheat',
  'White yam',
  'Water yam',
] as const;

export const POPULAR_NIGERIAN_CROPS = [
  'Cassava',
  'White yam',
  'Rice',
  'Maize',
  'Tomato',
  'Beans (Cowpea)',
  'Pepper (Ata rodo)',
  'Plantain',
] as const;